# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m5T4_7MvDJu4TexEV7sc3Po5wdXzxLHQ
"""

psw = "Rock.43"
name = input("Enter your name:")
if name == "Ahmet" : print ("Hello, Ahmet! The password is: Rock.43")
else : print("Hello {}! See you later.".format(name))

psw = "Rock.43"
name = input("Enter your name:")
if name == "Ahmet" : print ("Hello, Ahmet! The password is: Rock.43")
else : print("Hello {}! See you later.".format(name))